# Generated by Django 4.2 on 2023-04-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
