# Generated by Django 4.2 on 2023-05-05 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='userProfile',
            new_name='user_profile',
        ),
    ]
